import type { CanvasNode, CanvasEdge } from "@/types/canvas"

export interface CanvasTemplate {
  id: string
  name: string
  description: string
  nodes: CanvasNode[]
  edges: CanvasEdge[]
}

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: "microservices",
    name: "Microservices Architecture",
    description: "A standard 3-tier gateway structure with isolated microservices, user authentication, and dedicated databases.",
    nodes: [
      {
        id: "gateway",
        type: "customNode",
        position: { x: 50, y: 150 },
        data: { label: "API Gateway", shape: "pill", color: "#331B00" },
        width: 120,
        height: 40,
        style: { width: 120, height: 40 },
      },
      {
        id: "auth_svc",
        type: "customNode",
        position: { x: 250, y: 50 },
        data: { label: "Auth Service", shape: "rectangle", color: "#2E1938" },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
      },
      {
        id: "user_svc",
        type: "customNode",
        position: { x: 250, y: 150 },
        data: { label: "User Service", shape: "rectangle", color: "#10233D" },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
      },
      {
        id: "order_svc",
        type: "customNode",
        position: { x: 250, y: 250 },
        data: { label: "Order Service", shape: "rectangle", color: "#062822" },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
      },
      {
        id: "auth_db",
        type: "customNode",
        position: { x: 450, y: 50 },
        data: { label: "Auth DB", shape: "cylinder", color: "#3A1726" },
        width: 100,
        height: 60,
        style: { width: 100, height: 60 },
      },
      {
        id: "user_db",
        type: "customNode",
        position: { x: 450, y: 150 },
        data: { label: "User DB", shape: "cylinder", color: "#3A1726" },
        width: 100,
        height: 60,
        style: { width: 100, height: 60 },
      },
      {
        id: "order_db",
        type: "customNode",
        position: { x: 450, y: 250 },
        data: { label: "Order DB", shape: "cylinder", color: "#3A1726" },
        width: 100,
        height: 60,
        style: { width: 100, height: 60 },
      },
    ],
    edges: [
      { id: "g-to-a", source: "gateway", target: "auth_svc", label: "validate", type: "customEdge" },
      { id: "g-to-u", source: "gateway", target: "user_svc", label: "request", type: "customEdge" },
      { id: "g-to-o", source: "gateway", target: "order_svc", label: "checkout", type: "customEdge" },
      { id: "a-to-adb", source: "auth_svc", target: "auth_db", type: "customEdge" },
      { id: "u-to-udb", source: "user_svc", target: "user_db", type: "customEdge" },
      { id: "o-to-odb", source: "order_svc", target: "order_db", type: "customEdge" },
    ],
  },
  {
    id: "cicd_pipeline",
    name: "CI/CD Deployment Pipeline",
    description: "A continuous integration and deployment flow from code commit, build, scan, staging to production release.",
    nodes: [
      {
        id: "git",
        type: "customNode",
        position: { x: 50, y: 110 },
        data: { label: "Code Push", shape: "circle", color: "#10233D" },
        width: 70,
        height: 70,
        style: { width: 70, height: 70 },
      },
      {
        id: "build",
        type: "customNode",
        position: { x: 170, y: 120 },
        data: { label: "Build & Test", shape: "hexagon", color: "#0F2E18" },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
      },
      {
        id: "docker",
        type: "customNode",
        position: { x: 320, y: 120 },
        data: { label: "Docker Image", shape: "rectangle", color: "#062822" },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
      },
      {
        id: "scan",
        type: "customNode",
        position: { x: 470, y: 105 },
        data: { label: "Security Scan", shape: "diamond", color: "#3C1618" },
        width: 80,
        height: 80,
        style: { width: 80, height: 80 },
      },
      {
        id: "staging",
        type: "customNode",
        position: { x: 600, y: 125 },
        data: { label: "Staging Deploy", shape: "pill", color: "#1F1F1F" },
        width: 110,
        height: 40,
        style: { width: 110, height: 40 },
      },
      {
        id: "approval",
        type: "customNode",
        position: { x: 760, y: 105 },
        data: { label: "Manual Review", shape: "diamond", color: "#331B00" },
        width: 80,
        height: 80,
        style: { width: 80, height: 80 },
      },
      {
        id: "prod",
        type: "customNode",
        position: { x: 890, y: 120 },
        data: { label: "Production", shape: "hexagon", color: "#2E1938" },
        width: 100,
        height: 50,
        style: { width: 100, height: 50 },
      },
    ],
    edges: [
      { id: "e1", source: "git", target: "build", type: "customEdge" },
      { id: "e2", source: "build", target: "docker", label: "success", type: "customEdge" },
      { id: "e3", source: "docker", target: "scan", type: "customEdge" },
      { id: "e4", source: "scan", target: "staging", label: "pass", type: "customEdge" },
      { id: "e5", source: "staging", target: "approval", type: "customEdge" },
      { id: "e6", source: "approval", target: "prod", label: "approved", type: "customEdge" },
    ],
  },
  {
    id: "event_driven",
    name: "Event-Driven System",
    description: "An asynchronous queue-based architecture featuring event producers, central Kafka broker, and consumer database sinks.",
    nodes: [
      {
        id: "clients",
        type: "customNode",
        position: { x: 50, y: 155 },
        data: { label: "Clients", shape: "pill", color: "#10233D" },
        width: 100,
        height: 40,
        style: { width: 100, height: 40 },
      },
      {
        id: "ingress",
        type: "customNode",
        position: { x: 200, y: 150 },
        data: { label: "Ingress Controller", shape: "rectangle", color: "#1F1F1F" },
        width: 120,
        height: 50,
        style: { width: 120, height: 50 },
      },
      {
        id: "broker",
        type: "customNode",
        position: { x: 380, y: 140 },
        data: { label: "Kafka Event Broker", shape: "hexagon", color: "#331B00" },
        width: 130,
        height: 70,
        style: { width: 130, height: 70 },
      },
      {
        id: "payment_consumer",
        type: "customNode",
        position: { x: 580, y: 50 },
        data: { label: "Payment Svc (Consumer)", shape: "rectangle", color: "#2E1938" },
        width: 150,
        height: 50,
        style: { width: 150, height: 50 },
      },
      {
        id: "notify_consumer",
        type: "customNode",
        position: { x: 580, y: 150 },
        data: { label: "Notification Svc (Consumer)", shape: "rectangle", color: "#062822" },
        width: 150,
        height: 50,
        style: { width: 150, height: 50 },
      },
      {
        id: "analytics_consumer",
        type: "customNode",
        position: { x: 580, y: 250 },
        data: { label: "Analytics Svc (Consumer)", shape: "rectangle", color: "#0F2E18" },
        width: 150,
        height: 50,
        style: { width: 150, height: 50 },
      },
      {
        id: "lake",
        type: "customNode",
        position: { x: 790, y: 145 },
        data: { label: "Data Lake", shape: "cylinder", color: "#3A1726" },
        width: 100,
        height: 60,
        style: { width: 100, height: 60 },
      },
    ],
    edges: [
      { id: "cli-to-ing", source: "clients", target: "ingress", label: "HTTPS", type: "customEdge" },
      { id: "ing-to-bro", source: "ingress", target: "broker", label: "publish", type: "customEdge" },
      { id: "bro-to-pay", source: "broker", target: "payment_consumer", label: "orders", type: "customEdge" },
      { id: "bro-to-not", source: "broker", target: "notify_consumer", label: "events", type: "customEdge" },
      { id: "bro-to-ana", source: "broker", target: "analytics_consumer", label: "metrics", type: "customEdge" },
      { id: "pay-to-lake", source: "payment_consumer", target: "lake", type: "customEdge" },
      { id: "not-to-lake", source: "notify_consumer", target: "lake", type: "customEdge" },
      { id: "ana-to-lake", source: "analytics_consumer", target: "lake", type: "customEdge" },
    ],
  },
]
